### PR TITLE
1.15 Support & Custom Fountain Heads

### PR DESCRIPTION
**Pull request by Chazza**
This PR adds Spigot 1.15 support to the plugin alongside custom head functionality for the fountains aspect, alongside various code cleanups along the way.

Huge thanks to @GiansCode for the donation in order to help the community benefit with this new version support and features.

In order for custom skulls, the config will look like so:
`settings:
  heads:
      test:
       - 'user_Gianluca'
       - '14600'
  prefix: '&8[&aBP&8]: '`

If heads database is installed, it'll use those otherwise it will use the Minecraft Texture URL.

### CODE REVIEW

**Comment by badbones69** [comment]
Thanks a lot for the PR. Looking over it now.

**Comment by badbones69** [comment]
So one issue I do see is that the config and data files were set to lowercase which is fine for newer servers but when loaded onto a server with an older version of block particles it will stop their old files from working. Ill set up a converter to switch to lowercase.

**Comment by badbones69** [comment]
Thanks a lot for the custom fountains option as well. That will make a great addition to the plugin. <3

**Comment by Chazza** [comment]
Awesome, no problem and yeah I lowercases everything as it looked cleaner personally.

Thanks for merging! Merry Christmas :)

**Comment by badbones69** [comment]
I did make a converter for it and since BP doesn't have lots of stuff to convert it was easy but with plugins with more options that is a different story. Well, hope you have a Merry Christmas as well and thanks again.

**Pull request merged**
